### ISSUE TITLE
Cannot set savePath setting. String does not match pattern

### ISSUE THREAD

**Issue by OfficialCRUGG** [sudoaugustin/tailwindcss-transpiler-vscode#3]
![image](https://user-images.githubusercontent.com/25248999/106026012-9df98300-60c9-11eb-91ca-84c6b0b5cbc1.png)
Hey there. I think the image above is pretty self explanatory. I get this error and don't really know how to fix it...

**Comment by sudoaugustin** [comment]
Add the / infornt of public

**Comment by sudoaugustin** [comment]
This extension is deprecate. Try [Tailpile](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.tailpile), it is more powerful. And extremely sorry for the late reply.
