### ISSUE TITLE
What theme is used on the screenshots?

### ISSUE THREAD

**Issue by ymatuhin** [sudoaugustin/tailwindcss-transpiler-vscode#4]

**Comment by sudoaugustin** [comment]
> 

**SynthWave 84**

https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode#:~:text=the%20activation%20function.-,Open%20your%20command%20palette%20with%20Ctrl%20%2B%20Shift%20%2B%20P%20or%20Shift,the%20chrome%20updates%2C%20see%20below.
