### ISSUE TITLE
Loops does not works (loops yet, but interpolation...)

### ISSUE THREAD

**Issue by Kcko** [sudoaugustin/tailwindcss-transpiler-vscode#6]
Hi,

code

```
@for $i from 1 to 4 {
    .test-#{$i} {
        color: blue;
    }
}

```

And in console i get this errror message https://bit.ly/3rCipWb

What can this plugin from native SCSS / SASS actually use and convert?

**Comment by sudoaugustin** [comment]
This extension is deprecate. Try [Tailpile](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.tailpile). And sry for this reply delay.
