### ISSUE TITLE
save path is going to visual code path

### ISSUE THREAD

**Issue by ajayda24** [sudoaugustin/tailwindcss-transpiler-vscode#7]
"tailwindTranspiler.savePath": "public/css"

I added this line in my settings.json, but the output file is going to C:\Users[username]\AppData\Local\Programs\Microsoft VS Code\ \

**Comment by sudoaugustin** [comment]
This extension is deprecate. Try [Tailpile](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.tailpile). And sry for this reply delay.
