### ISSUE TITLE
how can i use jit mode

### ISSUE THREAD

**Issue by callect** [sudoaugustin/tailwindcss-transpiler-vscode#8]
I like this extensions, can i use tailwind jit mode with it.

**Comment by sudoaugustin** [comment]
Try [Tailpile](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.tailpile). I just made this. It comes with tailwindcss2.2.19 buit-in. It also support upgrading the tailwindcss to `latest` & `next` version.
